#ifndef _KATARINA_STD_H
#define _KATARINA_STD_H

#define KATARINA_Q_APPLICATION_NAME "katarina"
#define KATARINA_Q_APPLICATION_DEVELOPER "Karin"
#define KATARINA_Q_APPLICATION_TIME "2016"
#define KATARINA_Q_APPLICATION_STATUS "devel"
#define KATARINA_Q_APPLICATION_VERSION "0.3.3harmattan1"


#endif
